# Copyright 2026 Octoprox Authors
# SPDX-License-Identifier: Apache-2.0

"""Tests for TLSCertManager CA generation and clustered bootstrap."""

import asyncio
import stat
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes

from api.core.tls_cert_manager import TLSCertManager
from api.db.redis import RedisClient


def _mgr(ca_dir: Path) -> TLSCertManager:
    return TLSCertManager(
        ca_cert_path=ca_dir / "octoprox-ca.crt",
        ca_key_path=ca_dir / "octoprox-ca.key",
    )


def _disk_fingerprint(path: Path) -> str:
    cert = x509.load_pem_x509_certificate(path.read_bytes())
    return cert.fingerprint(hashes.SHA256()).hex()


def _mem_fingerprint(mgr: TLSCertManager) -> str:
    assert mgr._ca_cert is not None  # loaded/generated by initialize/bootstrap
    return mgr._ca_cert.fingerprint(hashes.SHA256()).hex()


class TestGenerateAndLoad:
    async def test_generates_ca_when_absent(
        self, redis_client: RedisClient, tmp_path: Path
    ) -> None:
        ca_dir = tmp_path / "ca"
        mgr = _mgr(ca_dir)
        await mgr.bootstrap(redis_client, "octoprox-1")

        assert mgr.ca_cert_path.exists()
        # Private key is written with restrictive permissions.
        assert stat.S_IMODE((ca_dir / "octoprox-ca.key").stat().st_mode) == 0o600
        # The atomic write leaves no temp files behind.
        assert sorted(p.name for p in ca_dir.iterdir()) == [
            "octoprox-ca.crt",
            "octoprox-ca.key",
        ]

    async def test_loads_existing_ca_idempotently(
        self, redis_client: RedisClient, tmp_path: Path
    ) -> None:
        ca_dir = tmp_path / "ca"
        first = _mgr(ca_dir)
        await first.bootstrap(redis_client, "octoprox-1")
        fingerprint = _disk_fingerprint(first.ca_cert_path)

        # A second manager over the same paths loads, not regenerates.
        second = _mgr(ca_dir)
        await second.bootstrap(redis_client, "octoprox-2")
        assert _mem_fingerprint(second) == fingerprint
        assert _disk_fingerprint(second.ca_cert_path) == fingerprint


class TestBootstrapCoordination:
    async def test_concurrent_bootstrap_yields_single_shared_ca(
        self, redis_client: RedisClient, tmp_path: Path
    ) -> None:
        # Three managers share one CA directory — as cluster instances share
        # one volume — and bootstrap concurrently against real Redis.
        ca_dir = tmp_path / "ca"
        managers = [_mgr(ca_dir) for _ in range(3)]

        await asyncio.gather(
            *(
                mgr.bootstrap(redis_client, f"octoprox-{i}")
                for i, mgr in enumerate(managers)
            )
        )

        # Exactly one CA on disk, with no temp leftovers from the race.
        assert sorted(p.name for p in ca_dir.iterdir()) == [
            "octoprox-ca.crt",
            "octoprox-ca.key",
        ]
        # Every instance ended up using the same CA — the whole point of the
        # shared volume, so leaf certs validate across all backends.
        fingerprints = {_mem_fingerprint(mgr) for mgr in managers}
        assert len(fingerprints) == 1
        assert fingerprints == {_disk_fingerprint(ca_dir / "octoprox-ca.crt")}

    async def test_bootstrap_loads_preexisting_ca(
        self, redis_client: RedisClient, tmp_path: Path
    ) -> None:
        ca_dir = tmp_path / "ca"
        seed = _mgr(ca_dir)
        await seed.bootstrap(redis_client, "octoprox-seed")
        fingerprint = _disk_fingerprint(seed.ca_cert_path)

        mgr = _mgr(ca_dir)
        await mgr.bootstrap(redis_client, "octoprox-late")
        assert _mem_fingerprint(mgr) == fingerprint
