title: Octoprox
description: A dynamic and flexible proxy manager that acts as an intelligent proxy aggregator
baseurl: ""

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

include:
  - "*.html"
  - "*.md"

