# Copyright 2026 Octoprox Authors
# SPDX-License-Identifier: Apache-2.0

"""Text the OpenVPN endpoint hands to the daemon and to devices.

Pure functions, so what the daemon is started with and what a device is
told can be tested without either.
"""

from __future__ import annotations

import re

from api.models.openvpn import OpenVpnPeer, OpenVpnServerSettings

# The ciphers both the daemon and every current client negotiate from. The
# fallback is for a client too old to negotiate (none that can import our
# profile is); naming one keeps the daemon from warning about it on every start.
DATA_CIPHERS = "AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305"
DATA_CIPHERS_FALLBACK = "AES-256-GCM"
_UNSAFE = re.compile(r"[^a-zA-Z0-9_.-]+")
_FILENAME_LIMIT = 64


def _inline(tag: str, body: str) -> list[str]:
    return [f"<{tag}>", body.strip(), f"</{tag}>"]


def render_server_conf(
    server: OpenVpnServerSettings,
    *,
    interface: str,
    port: int,
    mtu: int,
    management_socket: str,
) -> str:
    """The daemon's configuration file, identity included.

    ``server`` sets up TLS server mode on the subnet with the gateway as the
    daemon's own address. Devices are not addressed from the pool: every
    connection is admitted through the management interface
    (``management-client-auth``, with ``auth-user-pass-optional`` so no
    username is asked of the device), which pushes the device's fixed
    address, so the tunnel address is the credential exactly as with WireGuard. The
    daemon drops packets a device sends from any other source address.
    Everything the device sends is routed into the tunnel and its DNS is
    the gateway, where the fake-IP resolver answers. The control channel is
    wrapped with tls-crypt, so the port answers nothing to a scanner.
    """
    network = server.network
    lines = [
        "# Generated by Octoprox; rewritten every time the endpoint starts.",
        f"server {network.network_address} {network.netmask}",
        "topology subnet",
        f"proto {'tcp-server' if server.protocol == 'tcp' else 'udp'}",
        f"port {port}",
        f"dev {interface}",
        "dev-type tun",
        f"tun-mtu {mtu}",
        'push "redirect-gateway def1"',
        f'push "dhcp-option DNS {server.gateway}"',
        f"keepalive {server.keepalive_interval} {server.keepalive_timeout}",
        "persist-key",
        "persist-tun",
        "remote-cert-tls client",
        "dh none",
        f"data-ciphers {DATA_CIPHERS}",
        f"data-ciphers-fallback {DATA_CIPHERS_FALLBACK}",
        "auth SHA256",
        f"management {management_socket} unix",
        "management-client-auth",
        # management-client-auth makes the daemon demand a username and password
        # from every client unless told otherwise; the certificate plus the peer
        # directory are the credential, profiles carry none.
        "auth-user-pass-optional",
        "verb 3",
        *_inline("ca", server.ca_cert),
        *_inline("cert", server.server_cert),
        *_inline("key", server.server_key),
        *_inline("tls-crypt", server.tls_crypt_key),
    ]
    return "\n".join(lines) + "\n"


def render_client_profile(peer: OpenVpnPeer, server: OpenVpnServerSettings) -> str:
    """A device's ``.ovpn`` profile with the CA, its certificate and key, and the tls-crypt key inline.

    One file, importable by OpenVPN Connect, routers and the command line
    client alike. ``remote-cert-tls server`` pins the endpoint to a server
    certificate of the install's CA. Nothing here is newer than OpenVPN 2.4,
    which is what router firmware tends to ship: the cipher list is the
    daemon's business (2.5+ ``data-ciphers`` would make a 2.4 client refuse
    the whole profile), and a 2.4 client negotiates from the same AEAD set.
    """
    lines = [
        f"# Octoprox device: {peer.name}",
        "client",
        "dev tun",
        f"proto {server.protocol}",
        f"remote {server.endpoint_host or '<set the public endpoint in Settings, OpenVPN>'} {server.endpoint_port}",
        "resolv-retry infinite",
        "nobind",
        "persist-key",
        "persist-tun",
        "remote-cert-tls server",
        "auth SHA256",
        "verb 3",
    ]
    if server.client_mtu:
        lines.append(f"tun-mtu {server.client_mtu}")
    lines += [
        *_inline("ca", server.ca_cert),
        *_inline("cert", peer.certificate),
        *_inline("key", peer.private_key),
        *_inline("tls-crypt", server.tls_crypt_key),
    ]
    return "\n".join(lines) + "\n"


def client_profile_filename(peer_name: str) -> str:
    """``<name>.ovpn`` with a stem every importer accepts."""
    stem = _UNSAFE.sub("-", peer_name.strip()).strip("-.")[:_FILENAME_LIMIT].rstrip("-.")
    return f"{stem or 'octoprox'}.ovpn"
